// @keepTs
// @ts-nocheck
/**
 * 偏转工具类
 *
 * @author [刘博](manba.lb)
 * @date 2023-11-08
 */
export declare class LocationOffsetUtils {
    static readonly d93 = 315936000000;
    static readonly e93: number;
    static readonly f93: number;
    private static readonly g93;
    private static readonly h93;
    private static readonly i93;
    private static readonly j93;
    private static readonly k93;
    private static readonly l93;
    private static readonly m93;
    private static readonly n93;
    private static readonly o93;
    private static readonly p93;
    private static readonly q93;
    private static readonly r93;
    private static readonly s93;
    /**
     * @param wg_lng WGS84经度
     * @param wg_lat WGS84纬度
     * @brief WGS84 to GCJ02
     */
    static wgs84ToGcj02(x91: number, y91: number): number[];
    private static t93;
    private static v93;
    private static w93;
    private static u93;
}
