// @keepTs
// @ts-nocheck
export declare class LogUtil {
    private static c94;
    private static d94;
    private static e94;
    private static h43;
    static i(b94: string, tag: string, format: string): void;
    static d(a94: string, tag: string, format: string): void;
    static w(z93: string, tag: string, format: string): void;
    static e(y93: string, tag: string, format: string): void;
}
