// @keepTs
// @ts-nocheck
export declare class XXTEA {
    private static c100;
    static encryptUint8Array(data: Uint8Array, key: Uint8Array): Uint8Array | undefined;
    static e100(v: number[], k: number[]): number[];
    static f100(data: Uint8Array, key: Uint8Array): Uint8Array | undefined;
    static g100(v: number[], k: number[]): number[];
    static l81(data: number[], o99: boolean): Uint8Array | undefined;
    static d100(data: Uint8Array, m99: boolean): number[];
}
