// @keepTs
// @ts-nocheck
import { p66 } from "../interface/IAMapNativeDelegate";
export declare class r162 {
    private readonly g102;
    private q210?;
    private r210?;
    private s210;
    private t210;
    constructor(p210: p66);
    private u210;
    /**
    * 检查是否需要展示
    */
    t164(): void;
    /**
    * 英文国际图
    */
    v210(): void;
    /**
    * 中文国际图
    */
    w210(): void;
    private x210;
    private y210;
}
