// @keepTs
// @ts-nocheck
import { n108 } from '../interface/bridge/ILocationViewBridge';
import { p66 } from '../interface/IAMapNativeDelegate';
export declare class x166 {
    private context;
    private l2;
    private l275;
    private m275;
    h177(): void;
    constructor(context: Context, map: p66, i275: n108);
    isSelect(): boolean;
    n275(select: boolean): void;
    setVisible(visible: boolean): void;
}
