// @keepTs
// @ts-nocheck
import { l109 } from '../interface/bridge/IZoomControllerViewBridge';
import { p66 } from '../interface/IAMapNativeDelegate';
export declare class i278 {
    private context;
    private g102;
    private o282;
    private p282;
    h177(): void;
    constructor(context: Context, map: p66, m282: l109);
    a167(l282: number): void;
    setZoomPosition(position: number): void;
    setVisible(isEnable: boolean): void;
    s111(i282: number, j282: number, k282: number): void;
}
