// @keepTs
// @ts-nocheck
import { x59 } from './IGLMapState';
export type q165 = (engineId: number, mapState?: x59) => void;
export type r165 = (engineId: number, mapState?: x59) => void;
export type s165 = (engineId: number, mapState?: x59) => void;
export type t165 = (engineId: number) => void;
export declare class q66 {
    private f166;
    private g166;
    private h166;
    private i166;
    constructor(b166: q165, c166: r165, d166: s165, e166: t165);
    t67(z165: number, a166?: x59): void;
    w67(x165: number, y165?: x59): void;
    y67(v165: number, w165?: x59): void;
    a68(u165: number): void;
}
