// @keepTs
// @ts-nocheck
/**
 * Use these variables when you tailor your ArkTS code. They must be of the const type.
 */
export declare const o = "11.1.0";
export declare const t = "release";
export declare const DEBUG = false;
export declare const u = "default";
/**
 * BuildProfile Class is used only for compatibility purposes.
 */
export default class a1 {
    static readonly o = "11.1.0";
    static readonly t = "release";
    static readonly DEBUG = false;
    static readonly u = "default";
}
