// @keepTs
// @ts-nocheck
export declare class q121 {
    private static readonly TAG;
    protected static readonly z123: number;
    static z122(second: number, data: ArrayBuffer): ArrayBuffer;
    /**
     * Return the string of due time.
     *
     * @param seconds The seconds.
     * @return the string of due time
     */
    private static a124;
    static i123(data: Int8Array): boolean;
    private static b124;
    static k123(data: Int8Array): Int8Array;
    static d124(original: Int8Array, from: number, to: number): Int8Array;
    static c124(data: Int8Array): boolean;
}
