// @keepTs
// @ts-nocheck
export declare class q1 {
    /**
     * 维度的最大值
     */
    static readonly b10: number;
    /**
     * 维度的最小值
     */
    static readonly c10: number;
    /**
     * 经度的最大值
     */
    static readonly d10: number;
    /**
     * 经度的最小值
     */
    static readonly e10: number;
    /**
     * 自动定位最小时间间隔（毫秒）
     */
    static readonly j23: number;
    /**
     * gpsFirst超时时间的最小值
     * @since 4.5.0
     */
    static readonly q23: number;
    /**
     * gpsFirst超时时间的最大值
     * @since 4.5.0
     */
    static readonly r23: number;
    /**
     * 自动系统（GPS）定位最小距离间隔（米）
     */
    static readonly i24: number;
}
