export function nativeSetAMapXComponentCallback(k342: number, p2: object);
//GLEngineMap
export function nativeInitParam(z341: string, p2: string, a342: string, b342: string, c342: string, d342: string, e342: string, f342: string, g342: string, h342: string, i342: number, j342: number);
export function nativeInitAMapEngineCallback(y341: bigint, p2: object);
export function nativeCreateAMapInstance(u341: number, p2: number, v341: number, w341: number, x341: boolean): bigint;
export function nativeInitContourLineOptions(t341: bigint, p2: boolean);
export function nativeInitNativeTextGenerate(s341: bigint, p2: object);
export function nativeGzipByteArrayDecompress(r341: Uint8Array): Uint8Array;
export function nativeCreateAMapEngineWithFrame(g341: bigint, p2: number, h341: number, i341: number, j341: number, k341: number, l341: number, m341: number, n341: number, o341: number, p341: number, q341: number);
export function nativeSetServiceViewRect(z340: number, p2: bigint, a341: number, b341: number, c341: number, d341: number, e341: number, f341: number);
export function nativeRenderAMap(y340: bigint, p2: number);
export function nativeIsEngineCreated(x340: bigint, p2: number): boolean;
export function nativeDestroy(w340: bigint, p2: number);
export function nativeDestroyRenderEnv(v340: bigint, p2: number);
export function nativeGetCurrentMapState(u340: number, p2: bigint): bigint;
export function nativeDestroyCurrentState(t340: bigint, p2: bigint);
export function nativePushRendererState(s340: number, p2: bigint);
export function nativePopRenderState(r340: number, p2: bigint);
export function nativeGetMapModeState(p340: number, p2: bigint, q340: boolean): Int32Array;
export function nativeSetMapModeAndStyle(n340: number, p2: bigint, o340: Int32Array): boolean;
export function nativeSetParameter(h340: number, p2: bigint, i340: number, j340: number, k340: number, l340: number, m340: number);
export function nativeGetSrvViewStateBoolValue(f340: number, p2: bigint, g340: number): boolean;
export function nativeSetSrvViewStateBoolValue(c340: number, p2: bigint, d340: number, e340: boolean);
export function nativeCreateOverlay(a340: number, p2: bigint, b340: number): bigint;
export function nativeDestroyOverlay(z339: number, p2: bigint);
export function nativeAddNativeOverlay(w339: number, p2: bigint, x339: number, y339: number): string;
export function nativeRemoveNativeOverlay(u339: number, p2: bigint, v339: string);
export function nativeRemoveNativeAllOverlay(t339: number, p2: bigint);
export function nativeGetGlOverlayMgrPtr(s339: number, p2: bigint): bigint;
export function nativeCreateTextureFromImage(q339: number, p2: bigint, r339: object): number;
export function nativeAddOverlayTexture(i339: number, p2: bigint, j339: number, k339: number, l339: number, m339: number, n339: object, o339: boolean, p339: boolean): boolean;
export function nativeSetOverlayPriorityOnly(h339: bigint, p2: number): void;
export function nativeSetIndoorBuildingToBeActive(d339: number, p2: bigint, e339: string, f339: number, g339: string);
export function nativeSetNaviLabelEnable(z338: number, p2: bigint, a339: boolean, b339: number, c339: number);
export function nativeSetSimple3DEnable(x338: number, p2: bigint, y338: boolean);
export function nativeSetStyleChangeGradualEnable(v338: number, p2: bigint, w338: boolean);
export function nativeSetRoadArrowEnable(t338: number, p2: bigint, u338: boolean);
export function nativeSetSetBackgroundTexture(r338: number, p2: bigint, s338: Uint8Array);
export function nativeSetTrafficEnable(p338: number, p2: bigint, q338: boolean);
export function nativeSetLabelEnable(n338: number, p2: bigint, o338: boolean);
export function nativeSetAllContentEnable(l338: number, p2: bigint, m338: boolean);
export function nativeSetProjectionCenter(i338: number, p2: bigint, j338: number, k338: number);
export function nativeSetRenderListenerStatus(h338: number, p2: bigint);
export function nativeSetBuildingEnable(f338: number, p2: bigint, g338: boolean);
export function nativeSetIndoorEnable(d338: number, p2: bigint, e338: boolean);
export function nativeSetOfflineDataEnable(b338: number, p2: bigint, c338: boolean);
export function nativeSetHighlightSubwayEnable(z337: number, p2: bigint, a338: boolean);
export function nativeGetCurTileIDs(w337: number, p2: bigint, x337: Int32Array, y337: number);
export function nativeGetNativeMapController(v337: number, p2: bigint): bigint;
export function nativeGetScreenShot(q337: number, p2: bigint, r337: number, s337: number, t337: number, u337: number): Int32Array;
export function nativeGetMapSDKVersion(): string;
export function nativeGetMapSDKDeps(): string;
export function nativeSetVectorOverlayPath(o337: number, p2: bigint, p337: string);
export function nativeAddGestureSingleTapMessage(l337: number, p2: bigint, m337: number, n337: number);
export function nativeHideBuildings(j337: number, p2: bigint, k337: object[]): number;
export function nativeShowHideBuildings(h337: number, p2: bigint, i337: number);
export function nativeSetRenderFlags(f337: number, p2: bigint, g337: boolean);
export function nativeSetBuildingTextureEnable(d337: number, p2: bigint, e337: boolean);
export function nativeSetCustomStyleTexture(b337: number, p2: bigint, c337: Uint8Array);
export function nativeSetCustomStyleData(y336: number, p2: bigint, z336: Uint8Array, a337: Uint8Array | undefined);
export function nativeCheckCustomStyleData(w336: number, p2: bigint, x336: Uint8Array): boolean;
export function nativeSetTrafficTexture(o336: number, p2: bigint, p336: Uint8Array, q336: bigint, r336: number, s336: number, t336: number, u336: number, v336: number);
export function nativeSetCustomThirdLayerStyle(m336: number, p2: bigint, n336: string);
export function nativeSetTerrainAuth(k336: number, p2: bigint, l336: boolean);
// GLNativeMapState
export function nativeNewInstance(j336: number, p2: bigint): bigint;
export function nativeSetMapState(h336: number, p2: bigint, i336: bigint);
export function nativeScreenToP20Point(f336: bigint, p2: number, g336: number): object;
export function nativeP20ToScreenPoint(c336: bigint, p2: number, d336: number, e336: number): object;
export function nativeSetMapCenter(a336: bigint, p2: number, b336: number);
export function nativeGetMapCenter(z335: bigint): object;
export function nativeGetMapCenterXDouble(y335: bigint): number;
export function nativeGetMapCenterYDouble(x335: bigint): number;
export function nativeGetMapZoom(w335: bigint): number;
export function nativeSetMapZoom(v335: bigint, p2: number);
export function nativeSetMapAngle(u335: bigint, p2: number);
export function nativeGetMapAngle(t335: bigint): number;
export function nativeSetCameraDegree(s335: bigint, p2: number);
export function nativeGetCameraDegree(r335: bigint): number;
export function nativeRecalculate(q335: bigint);
export function nativeStateDestroy(p335: bigint, p2: bigint);
export function nativeGetViewMatrix(o335: bigint): Float64Array;
export function nativeGetProjectionMatrix(n335: bigint): Float64Array;
export function nativeGetSkyHeight(m335: bigint): number;
export function nativeGetGLUnitWithWin(l335: bigint, p2: number): number;
export function nativeGetPixel20Bound(j335: bigint, p2: number, k335: number): object;
export function nativeCalMapZoomScalefactor(g335: bigint, p2: number, h335: number, i335: number): number;
export function nativeCalculateMapZoom(b335: bigint, p2: number, c335: number, d335: number, e335: number, f335: number): number;
// ResourceCallback
export function nativeCallSuccess(a335: bigint, p2: object);
export function nativeCallFailed(z334: bigint, p2: string);
export function nativeCallCancel(y334: bigint);
// AMapNativeGlOverlayLayer
export function nativeCreateOpenOverlay(w334: bigint, p2: string, x334: object);
export function nativeRemoveOpenOverlay(v334: bigint, p2: string);
export function nativeUpdateOptions(t334: bigint, p2: string, u334: object);
export function nativeRender(q334: bigint, p2: number, r334: number, s334: boolean);
export function nativeClear(p334: bigint, p2: string[]);
export function nativeContain(n334: bigint, p2: object, o334: number): string;
export function nativeGetCurrentParticleNum(m334: bigint, p2: string): number;
export function nativeGetNativeOverlayProperties(j334: bigint, p2: string, k334: string, l334: object[]): object;
export function nativeDestroyOverlayLayer(i334: bigint);
export function nativeCreateOverlayLayer(h334: bigint, p2: object): bigint;
export function nativeSet2Top(g334: bigint, p2: string);
export function nativeShowInfoWindow(f334: bigint, p2: string);
export function nativeHideInfoWindow(e334: bigint);
export function nativeRedrawInfoWindow(d334: bigint);
export function nativeGetMapScreenOverlays(c334: bigint): string[];
export function nativeOnInfoWindowTap(a334: bigint, p2: number, b334: number): boolean;
export function nativeSetInfoWindowShown(y333: bigint, p2: string, z333: boolean);
export function nativeSetFlingState(x333: bigint, p2: boolean);
export function nativeClearTileCache(w333: bigint);
export function nativeCheckInBounds(v333: bigint, p2: string): boolean;
// AMapGLOverlayCreator
export function nativeCreateMarker(t333: bigint, p2: string, u333: object);
export function nativeUpdateMarker(r333: bigint, p2: string, s333: object);
export function nativeCreateHeatMap(p333: bigint, p2: string, q333: object);
export function nativeUpdateHeatMap(n333: bigint, p2: string, o333: object);
export function nativeCreateHeatMapOverlay(l333: bigint, p2: string, m333: object);
export function nativeUpdateHeatMapOverlay(j333: bigint, p2: string, k333: object);
export function nativeCreateTileOverlay(h333: bigint, p2: string, i333: object);
export function nativeUpdateTileOverlay(f333: bigint, p2: string, g333: object);
export function nativeCreatePolyline(d333: bigint, p2: string, e333: object);
export function nativeUpdatePolyline(b333: bigint, p2: string, c333: object);
export function nativeCreateMultiPointOverlay(z332: bigint, p2: string, a333: object);
export function nativeUpdateMultiPointOverlay(x332: bigint, p2: string, y332: object);
export function nativeCreateArc(v332: bigint, p2: string, w332: object);
export function nativeUpdateArc(t332: bigint, p2: string, u332: object);
export function nativeCreatePolygon(r332: bigint, p2: string, s332: object);
export function nativeUpdatePolygon(p332: bigint, p2: string, q332: object);
export function nativeCreateCircle(n332: bigint, p2: string, o332: object);
export function nativeUpdateCircle(l332: bigint, p2: string, m332: object);
export function nativeCreateGL3DModel(j332: bigint, p2: string, k332: object);
export function nativeUpdateGL3DModel(h332: bigint, p2: string, i332: object);
export function nativeCreateGroundOverlay(f332: bigint, p2: string, g332: object);
export function nativeUpdateGroundOverlay(d332: bigint, p2: string, e332: object);
// AMapGLOverlayFuncOperator
export function nativeSetMarkerClickable(b332: bigint, p2: string, c332: boolean);
export function nativeGetMarkerClickable(a332: bigint, p2: string): boolean;
export function nativeIsInfoWindowShown(z331: bigint, p2: string): boolean;
export function nativeGetMarkerInfoWindowOffset(y331: bigint, p2: string): object;
export function nativeGetMarkerScreenPos(x331: bigint, p2: string): object;
export function nativeGetPosition(w331: bigint, p2: string): object;
export function nativeGetAlpha(v331: bigint, p2: string): number;
export function nativeGetRotateAngle(u331: bigint, p2: string): number;
// GLOverlay
export function nativeGetType(t331: bigint): number;
export function nativeGetSubType(s331: bigint): number;
export function nativeRemoveItem(r331: bigint, p2: number);
export function nativeRemoveAll(q331: bigint);
export function nativeGetCount(p331: bigint): number;
export function nativeSetVisible(o331: bigint, p2: boolean);
export function u156(n331: bigint): boolean;
export function nativeSetClickable(m331: bigint, p2: boolean);
export function nativeIsClickable(l331: bigint): boolean;
export function nativeSetOverlayOnTop(k331: bigint, p2: boolean);
export function nativeSetMinDisplayLevel(j331: bigint, p2: number);
export function nativeSetMaxDisplayLevel(i331: bigint, p2: number);
export function nativeSetOverlayPriority(h331: bigint, p2: number);
export function nativeGetOverlayPriority(g331: bigint): number;
// GLCrossVector
export function nativeAddVectorData(e331: bigint, p2: Int32Array, f331: Uint8Array): number;
export function nativeAddVectorCar(b331: bigint, p2: number, c331: number, d331: number);
export function nativeSetArrowResId(z330: bigint, p2: boolean, a331: number);
export function nativeSetCarResId(y330: bigint, p2: number);
export function nativeSetBackgroundResId(x330: bigint, p2: number);
export function nativeInitTextureCallback(v330: bigint, p2: object, w330: boolean);
// GLOverlayBundle
export function nativeAddGLOverlay(t330: bigint, p2: bigint, u330: bigint);
export function nativeAddGLOverlayEx(q330: bigint, p2: bigint, r330: bigint, s330: number);
export function nativeSortAllGLOverlay(p330: bigint);
export function nativeRemoveGLOverlay(o330: bigint, p2: bigint);
export function nativeRemoveGLOverlayEx(m330: bigint, p2: bigint, n330: number);
export function nativeClearAllGLOverlay(l330: bigint, p2: boolean);
export function nativeOnSingleTapPointOverlay(i330: bigint, p2: number, j330: number, k330: Int32Array): boolean;
export function nativeOnSingleTapLineOverlay(f330: bigint, p2: number, g330: number, h330: Int32Array): boolean;
// NetworkProxyManager
export function nativeCreateNetworkProxy(e330: object): bigint;
export function nativeInitNetworkProxy(d330: bigint);
export function nativeDestroyNetworkProxy(c330: bigint);
export function nativeReceiveNetData(a330: Uint8Array, p2: bigint, b330: number);
export function nativeFinishDownLoad(z329: bigint);
export function nativeCancelDownLoad(y329: bigint);
export function nativeFailedDownLoad(x329: bigint, p2: number);
export function nativeSetOverseaEnable(w329: bigint, p2: boolean);
// GlyphLoader
export function nativeCreateGlyphLoader(): bigint;
export function nativeDestroyGlyphLoader(v329: bigint);
// AMapUIThread
export function nativeExecuteUIThread();
