// @keepTs
// @ts-nocheck
/**
 * AAID 配置类
 */
export declare class x4 {
    /**
     * AAID高德转发服务域名
     */
    static readonly y4: string;
    static readonly z4: string;
    /**
     * 默认间隔一天请求刷新一次aaid
     */
    static readonly a5: number;
    /**
     * AAID更新时间间隔
     */
    static b5: number;
    /**
     * AAID是否可以本地默认值
     */
    static readonly c5: boolean;
    /**
     * AAID是否可用，本地默认值true 可用，云控可配置
     */
    static d5: boolean;
    static readonly e5: string;
}
