// @keepTs
// @ts-nocheck
import { l109, b111, c111, d111, e111, f111 } from '../interface/bridge/IZoomControllerViewBridge';
export declare class p12 implements l109 {
    private k111?;
    private l111?;
    private m111?;
    private n111?;
    private o111?;
    f15(event: TouchEvent): void;
    g15(event: TouchEvent): void;
    p111(listener: d111): void;
    q111(listener: e111): void;
    d14(listener: c111): void;
    r111(position: number): void;
    s111(h111: number, i111: number, j111: number): void;
    e14(g111: f111): void;
    f14(listener: b111): void;
    t111(visible: boolean): void;
}
