// @keepTs
// @ts-nocheck
import { j55 } from './Rom';
export declare class RomIdentifier {
    private static s55;
    static t55(): j55;
    static getDeviceType(): string;
    /**
     * 获取设备厂家名称
     *
     * @returns
     */
    static x55(): string;
    /**
     * 获取设备品牌
     * @returns
     */
    static y55(): string;
    /**
     * 外部产品系列
     * @returns
     */
    static z55(): string;
    /**
     * 发行版系统名称。
  
     * @returns
     */
    static u55(): string;
    /**
     * 发行版系统版本号。
  
     * @returns
     */
    static w55(): string;
    /**
     * 发行版系统api版本。
  
     * @returns
     */
    static v55(): number;
    /**
     * 发行版系统类型。
  
     * @returns
     */
    static a56(): string;
}
