// @keepTs
// @ts-nocheck
export declare class s130 {
    private static readonly m136;
    private static readonly n136;
    private static readonly o136;
    private static readonly p136;
    static h135(event: GestureEvent): number;
    static o135(e136: number, f136: number, g136: number, h136: number): number;
    static q136(velocity: number): number;
    private static r136;
    static t136(velocity: number): number;
    private static s136;
    static u136(num: number): number;
    static k135(): number;
}
