export class ChString{
  public static readonly Kilometer = "\u516c\u91cc";// "公里";
  public static readonly Meter = "\u7c73";// "米";
  public static readonly ByFoot = "\u6b65\u884c";// "步行";
  public static readonly To = "\u53bb\u5f80";// "去往";
  public static readonly Station = "\u8f66\u7ad9";// "车站";
  public static readonly TargetPlace = "\u76ee\u7684\u5730";// "目的地";
  public static readonly StartPlace = "\u51fa\u53d1\u5730";// "出发地";
  public static readonly About = "\u5927\u7ea6";// "大约";
  public static readonly Direction = "\u65b9\u5411";// "方向";

  public static readonly GetOn = "\u4e0a\u8f66";// "上车";
  public static readonly GetOff = "\u4e0b\u8f66";// "下车";
  public static readonly Zhan = "\u7ad9";// "站";

  public static readonly cross = "\u4ea4\u53c9\u8def\u53e3"; // 交叉路口
  public static readonly type = "\u7c7b\u522b"; // 类别
  public static readonly address = "\u5730\u5740"; // 地址
  public static readonly PrevStep = "\u4e0a\u4e00\u6b65";
  public static readonly NextStep = "\u4e0b\u4e00\u6b65";
  public static readonly Gong = "\u516c\u4ea4";
  public static readonly ByBus = "\u4e58\u8f66";
  public static readonly Arrive = "\u5230\u8FBE";// 到达
}