// @keepTs
// @ts-nocheck
export declare class Constants {
    static s2: string;
    static g64: string;
    static i91: string;
    static d64: string;
    static m90: string;
    static e64: string;
    static f64: string;
    static m65: string;
    static l65: string;
    static j65: string;
    static c64: string;
    static k65: string;
    static i65: string;
    static x90: string;
    static a64: string;
    static o90: string;
    static l90: string;
    static h64: string;
}
