// @keepTs
// @ts-nocheck
export declare class f73 {
    static u93(b: Uint8Array, startIndex: number): number;
    static getLong(b: Uint8Array, startIndex: number): bigint;
    static g237(b: Uint8Array, startIndex: number): number;
    static h237(b: Uint8Array, startIndex: number): number;
    static i237(b: Uint8Array, startIndex: number): number;
    static j237(b: Uint8Array, startIndex: number): number;
    static k237(i236: number): Uint8Array;
    static l237(g236: number): Uint8Array;
    static m237(b: Uint8Array, startIndex: number): number;
    static writeInt(src: Uint8Array, index: number, d236: number): void;
    static writeShort(src: Uint8Array, index: number, b236: number): void;
    static n237(src: Uint8Array, y235: number, dest: Uint8Array, z235: number, size: number): void;
    static o237(s: string): Uint8Array;
    static getString(b: Uint8Array, index: number, size: number): string;
    static q181(b: Uint8Array, index: number, size: number): Uint8Array;
}
