// @keepTs
// @ts-nocheck
export declare class w106 {
    /**
     * 扩展屏幕1（吉利KC2仪表盘使用）
     */
    static readonly f244: number;
    static readonly g244: number;
    static readonly h244: number;
    static readonly i244: number;
    static readonly j244: number;
    static readonly k244: number;
    /** 无效引擎ID*/
    static readonly l244: number;
    /** 主图*/
    static readonly c107: number;
    /** 鹰眼小地图*/
    static readonly m244: number;
    /** 扩展屏幕1（吉利KC2仪表盘使用）*/
    static readonly n244: number;
    /** 扩展屏幕1鹰眼*/
    static readonly o244: number;
    /** 扩展屏幕2*/
    static readonly p244: number;
    /** 扩展屏幕2鹰眼*/
    static readonly q244: number;
    /** 扩展屏幕3*/
    static readonly r244: number;
    /** 扩展屏幕3鹰眼*/
    static readonly s244: number;
    static readonly t244: number;
    static readonly u244: number;
    static readonly v244: number;
    static readonly w244: number;
    static readonly x244: number;
    static readonly y244: number;
    static z244(context: Context, resName: string): Uint8Array | null;
    static a245(context: Context, e244: number): number;
    static b245(context: Context, d244: number): number;
    /**
     * 从string.xml资源文件中获取字符串
     *
     * @param context
     * @param resId
     * @return
     */
    static getString(context: Context, resId: number): string;
    static c245(str: string | null): boolean;
    /**
     * Get application version name by context
     */
    static d245(context: Context): string;
}
