// @keepTs
// @ts-nocheck
export declare class y52 {
    static readonly k246: string;
    static readonly l246: string;
    static readonly m246: string;
    static readonly n246: string;
    static readonly o246: string;
    static readonly p246: string;
    static readonly q246: string;
    static readonly r246: string;
    static readonly s246: string;
    static readonly t246: string;
    static readonly u246: string;
    static readonly v246: string;
    static readonly w246: string;
    static readonly x246: string;
    static readonly y246: string;
    static readonly z246: string;
    static readonly a247: string;
    static readonly b247: string;
    /**
     * JS数组对象
     */
    static readonly c247: string;
    /**
     * JS padding对象 上下左右
     */
    static readonly d247: string;
    /**
     * 空json
     */
    static readonly e247: string;
    /**
     * Js icon对象
     */
    static f247: string;
    /**
     * 多彩线
     */
    static g247: string;
    static h247: string;
    static readonly a59: number;
}
