// @keepTs
// @ts-nocheck
/**
 * ClassName:Util <br/>
 * Function: TODO ADD FUNCTION. <br/>
 * Reason:   TODO ADD REASON. <br/>
 * Date:     2015年11月12日 下午4:48:50 <br/>
 * @author yiyi.qi
 * @version
 * @since JDK 1.6
 * @see
 */
export declare class RegionUtil {
    private static readonly i52;
    private static readonly j52;
    private static readonly k52;
    private static readonly WIDTH;
    private static readonly HEIGHT;
    /** 切片尺寸*/
    private static readonly l52;
    /** 0级切图每像素代表的距离*/
    private static readonly m52;
    /** 切图的最大边界值*/
    private static readonly n52;
    /**
     * 给定经纬度是不是在中国的判断
     *
     * @param lat
     * @param lng
     * @return
     */
    static isChina(e249: number, f249: number): boolean;
}
