// @keepTs
// @ts-nocheck
/**
 * 存放某种类型对应的mainkey 和subkey
 * 外部配置文件和引擎样式之间的桥梁
 */
export declare class i217 {
    static readonly n217: string;
    static readonly o217: string;
    static readonly p217: string;
    static readonly q217: string;
    static readonly r217: string;
    static readonly s217: string;
    static readonly t217: number;
    mainKey: number;
    subKey: number[];
    /**
     * 类型表示
     */
    u217: number;
    /**
     * 唯一标识
     */
    v217: number;
    w217: string;
    x217: string;
    describe: string;
    constructor(j217: number, k217: number[], l217: string, m217: string, describe: string);
}
