// @keepTs
// @ts-nocheck
export declare class e53 {
    /**
     * 样式文件版本号
     */
    private version;
    /**
     * 样式文件md5值
     */
    private a218;
    /**
     * 样式文件生成时间
     */
    private time;
    /**
     * 样式文件内容
     */
    private b218;
    getVersion(): string;
    setVersion(version: string): void;
    c218(): string;
    d218(z217: string): void;
    getTime(): string;
    setTime(time: string): void;
    i59(): string;
    e218(y217: string): void;
}
