// @keepTs
// @ts-nocheck
import { j107 } from './IBlankViewBridge';
import { u107 } from './ICompassViewBridge';
import { n108 } from './ILocationViewBridge';
import { j109 } from './IScaleViewBridge';
import { k109 } from './IWaterMarkerViewBridge';
import { l109 } from './IZoomControllerViewBridge';
export interface y108 {
    o13(): j107;
    r13(): n108;
    u13(): u107;
    y13(): j109;
    a14(): k109;
    c14(): l109;
}
