// @keepTs
// @ts-nocheck
import { l72 } from '../../AMapXComponentDelegate';
export interface w99 {
    x14(): XComponentController;
    i89(delegate: l72): void;
    onSurfaceCreated(instance: bigint, engineId: string, width: bigint, height: bigint): void;
    onSurfaceChanged(instance: bigint, engineId: string, width: bigint, height: bigint): void;
    onSurfaceDestroyed(instance: bigint, engineId: string): void;
    y14(engineId: string): void;
    z14(engineId: string): void;
}
