// @keepTs
// @ts-nocheck
import { w137 } from './AbstractOhglAnimationParam';
export declare class e139 extends w137 {
    f139: number;
    g139: number;
    h139: number;
    i139: number;
    constructor();
    reset(): void;
    y138(x: number, y: number): void;
    z138(x: number, y: number): void;
    j139(): number;
    k139(): number;
    l139(): number;
    m139(): number;
    n139(): number;
    o139(): number;
    j138(): void;
}
