// @keepTs
// @ts-nocheck
export declare abstract class i137 {
    static readonly j137: number;
    static readonly k137: number;
    static readonly l137: number;
    static readonly m137: number;
    static readonly n137: number;
    static readonly o137: number;
    static readonly p137: number;
    /**
     * 挖宝模块，宝箱marker动画Interpolator
     */
    static readonly q137: number;
    static readonly d96: number;
    protected duration: number;
    protected r137: boolean;
    protected startTime: number;
    protected s137: number;
    constructor();
    t137(): boolean;
    isValid(): boolean;
    /**
     * 执行动画
     * @param param 动画参数
     */
    abstract u137(param: Object): void;
}
