// @keepTs
// @ts-nocheck
export declare abstract class w137 {
    protected a138: number;
    protected factor: number;
    protected b138: number;
    protected c138: number;
    protected d138: boolean;
    protected e138: boolean;
    protected f138: boolean;
    protected g138: boolean;
    protected static h138(z137: number): number;
    reset(): void;
    i138(): boolean;
    k138(): number;
    l138(x137: number): void;
    t138(type: number, factor: number): void;
    u138(): number;
    /**
     * 参数检查
     */
    abstract j138(): void;
    constructor();
}
