// @keepTs
// @ts-nocheck
/**
 * 常量集合

 */
export declare class v137 {
    /***************ADGLAnimation*********************/
    static readonly e140: number;
    static readonly m138: number;
    static readonly n138: number;
    static readonly o138: number;
    static readonly p138: number;
    static readonly y139: number;
    static readonly f140: number;
    static readonly g140: number;
    static readonly h140: number;
    static readonly d139: number;
    static readonly i140: number;
    static readonly q138: number;
    static readonly j140: number;
    static readonly k140: number;
    static readonly r138: number;
    static readonly l140: number;
    static readonly m140: number;
    static readonly n140: number;
    static readonly s138: number;
    static readonly o140: number;
    static readonly p140: number;
}
