// @keepTs
// @ts-nocheck
import { i137 } from './AbstractOhglAnimation';
export declare class j141 extends i137 {
    constructor(duration: number, centerX: number, centerY: number);
    reset(): void;
    c142(velocityX: number, velocityY: number): void;
    d142(param: Object): void;
    f142(param: Object | undefined): void;
    u137(param: Object): void;
    private velocityX;
    private velocityY;
    private e142?;
    private a142?;
    private b142;
    private g141;
    private w141;
    private x141;
    private y141;
    private z141;
}
