// @keepTs
// @ts-nocheck
import { Point } from '../../api/model/Point';
import { i137 } from './AbstractOhglAnimation';
import { v138 } from './AbstractOhglAnimationParam1V';
export declare class y144 extends i137 {
    reset(): void;
    f142(param: Object): void;
    constructor(duration: number);
    w145(g145: number, type: number, h145: Point | null): void;
    u137(param: Object): void;
    private b142;
    private o145;
    private p145;
    private q145;
    private r145;
    private s145;
    private n145;
    private t145;
    private u145;
    protected v145?: v138;
}
