// @keepTs
// @ts-nocheck
import { SDKInfo } from "../SDKInfo";
export declare class f30 {
    static readonly s30: number;
    static readonly t30: number;
    static readonly u30: number;
    protected static v30: f30;
    protected w30: boolean;
    static x30(e: Error, r30: string, methodName: string): void;
    y30(m30: SDKInfo, msg: string, n30: string, o30: string): void;
    protected x30(e: Error, q30: number, r30: string, methodName: string): void;
    protected z30(/* todo : final Context context, */ k30: SDKInfo, l30: boolean): void;
    protected a31(i30: SDKInfo, j30: string): void;
    protected b31(g30: SDKInfo, h30: string, key: string): void;
    protected c31(): void;
}
