// @keepTs
// @ts-nocheck
import { j17 } from './UpdateStrategy';
export declare class m63 extends j17 {
    private readonly l64;
    private readonly m64;
    private readonly n64;
    private readonly o64;
    private readonly p64;
    private readonly context;
    private readonly preferences;
    private readonly q64;
    private constructor();
    static create(context: Context, z63: boolean, a64?: number, b64?: number, c64?: string, d64?: number, e64?: j17): m63;
    protected x17(): boolean;
    u17(): number;
    a59(o63: number): void;
    z58(flag: boolean): void;
    y58(): boolean;
    private r64;
}
