// @keepTs
// @ts-nocheck
import { l40 } from './StatisticsEntity';
import common from '@ohos.app.ability.common';
type Context = common.UIAbilityContext;
export declare class k40 {
    private static u66;
    private static v66;
    private static w66;
    private static x66;
    private static y66;
    /**
     * 更新离线日志配置（对应 Java 两个重载方法）
     */
    static z66(q66: number, r66: boolean, maxSize: number, s66?: number): void;
    private static o16;
    static e44(p66: l40, context: Context): void;
    static i44(o66: l40[], context: Context): void;
    static c67(n66: l40[] | null, context: Context): void;
    private static a67;
    private static b67;
    private static i61;
    static d67(context: Context): void;
    private static e67;
}
export {};
