// @keepTs
// @ts-nocheck
export { o } from './src/main/ets/components/mainpage/MainPage';
export { AMapLocationManager, IAMapLocationListener } from './src/main/ets/com/amap/interface/AMapLocationManager';
export { AMapLocationManagerImpl } from './src/main/ets/com/amap/location/AMapLocationManagerImpl';
export { AMapLocation, AMapLocationMoreType } from './src/main/ets/com/amap/location/AMapLocation';
export { AMapLocationOption } from './src/main/ets/com/amap/location/AMapLocationOption';
export { AMapLocationReGeocodeLanguage, AMapLocationType, AMapLocationErrorCode } from './src/main/ets/com/amap/interface/AMapLocationCommonObj';
export { AMapLocationReGeo } from './src/main/ets/com/amap/interface/AMapLocationReGeocode';
export { AMapLocationErrorInfo } from './src/main/ets/com/amap/location/AMapLocationErrorInfo';
export { GeoFenceClient } from './src/main/ets/com/amap/fence/GeoFenceClient';
export { Utils } from './src/main/ets/com/amap/utils/Utils';
export { GeoFence } from './src/main/ets/com/amap/fence/GeoFence';
export { DPoint } from './src/main/ets/com/amap/location/DPoint';
export { GeoFenceListener } from './src/main/ets/com/amap/fence/GeoFenceListener';
export { Constants } from './src/main/ets/com/amap/utils/Constants';
export { Handler, Message } from './src/main/ets/com/amap/utils/Handler';
export { CoordinateConverter } from './src/main/ets/com/amap/location/CoordinateConverter';
export { CoordType, valueOfCoordType, getValuesOfCoordType } from "./src/main/ets/com/amap/location/CoordType";
export { AMapLocationMode, AMapLocationProtocol, AMapLocationClientOption } from "./src/main/ets/com/amap/location/AMapLocationClientOption";
