// @keepTs
// @ts-nocheck
export declare class x29<E> {
    private static readonly j36;
    private k36?;
    private l36?;
    private m36?;
    private mSize?;
    get(key: number): E | undefined;
    n36(key: number, h36: E | undefined): E | undefined;
    private static o36;
    put(key: number, value: E): void;
    private p36;
    static q36(a36: number): number;
    static r36(y35: number): number;
}
