// @keepTs
// @ts-nocheck
export declare class InitParam {
    mRootPath: string;
    mConfigPath: string;
    mConfigContent: string;
    d68: string;
    mOfflineDataPath: string;
    mP3dCrossPath: string;
    mIntersectionResPath: string;
}
export declare class MapViewInitParam {
    engineId: number;
    x: number;
    y: number;
    width: number;
    height: number;
    screenWidth: number;
    screenHeight: number;
    screenScale: number;
    textScale: number;
    mapZoomScale: number;
    taskThreadCount: number;
}
