// @keepTs
// @ts-nocheck
export type c100 = (instance: bigint, engineId: string, width: bigint, height: bigint) => void;
export type d100 = (instance: bigint, engineId: string, width: bigint, height: bigint) => void;
export type e100 = (instance: bigint, engineId: string) => void;
export type f100 = (engineId: string) => void;
export type g100 = (engineId: string) => void;
export declare class l72 {
    private m100;
    private n100;
    private o100;
    private p100;
    private q100;
    constructor(h100: c100, i100: d100, j100: e100, k100: f100, l100: g100);
    get c100(): c100;
    get d100(): d100;
    get e100(): e100;
    get f100(): f100;
    get g100(): g100;
}
