// @keepTs
// @ts-nocheck
import common from "@ohos.app.ability.common";
import { p66 } from './interface/IAMapNativeDelegate';
export declare class d73 {
    private static g101;
    private static readonly TAG;
    private context;
    private h101;
    private i101;
    protected j101?: p66;
    constructor(context: common.Context);
    e89(reference: p66): void;
    u63(delay: number): void;
    destroy(): void;
    private m101;
    private n101;
    private n106;
    private m106;
}
export declare class z105 {
    info: string;
    z101: string;
    status: string;
    o101: boolean;
}
