// @keepTs
// @ts-nocheck
import { Rect } from '../api/model/Rect';
export declare class w24 {
    /**
     * 背景区域
     */
    p106: Rect | null;
    /**
     * 背景颜色
     */
    q106: number;
    /**
     * 箭头边线颜色
     */
    r106: number;
    /**
     * 箭头边线宽度
     */
    s106: number;
    /**
     * 箭头内部宽度
     */
    t106: number;
    /**
     * 箭头内部颜色
     */
    u106: number;
    /**
     * 路口图模式:true-白天,false-黑夜
     */
    v106: boolean;
}
