// @keepTs
// @ts-nocheck
import { SDKInfo } from '@amap/amap_lbs_common';
/**
 * 全局常量
 * @since 1.0.0
 *
 */
export declare class z47 {
    /**
     * 设置为true的时候会弹出Toast以及打印日志
     */
    static readonly q114: boolean;
    /**
     * 请求是需要传递的包名
     */
    static readonly r114: string;
    static readonly s114: string;
    static readonly t114: string;
    static readonly u114: string;
    static readonly v114: string;
    static readonly w114: string;
    static readonly x114: string;
    static readonly y114: string;
    static readonly z114: string;
    static readonly a115: string;
    static readonly VERSION: string;
    /**
     * 出云控包时需要修改。
     */
    static readonly b115: string;
    static readonly c115: string;
    static resolution: number;
    static readonly n103: string;
    static packageName: string;
    /**
     * 海外栅格图
     */
    static readonly d115: string;
    /**
     * 2D高清图
     */
    static readonly e115: string;
    static readonly LINE_WIDTH: number;
    static readonly f115: string;
    static readonly g115: string;
    static readonly h115: string;
    static readonly i115: string;
    static readonly j115: string;
    static readonly m105: string;
    static readonly k115: string;
    /**
     * AE8访问取图服务是需要添加此字段
     * @since V5.0.0
     */
    static readonly l115: string;
    /**
     * aos channel amap7对应的key
     */
    static readonly m115: string;
    static readonly n115: string;
    static readonly o115: number;
    static p115?: SDKInfo;
    static readonly URL: string;
    static readonly q115: string;
    static readonly r115: number;
    static readonly s115: number;
    static readonly t115: number;
    static readonly u115: number;
    static readonly v115: number;
    static readonly DEBUG = false;
    static readonly TAG: string;
    static readonly w115: number;
    static readonly x115: number;
    static readonly y115: string;
    static readonly z115: string;
    /**
     * 云控错误日志的开关
     */
    static readonly r105: string;
    /**
     * 记录离线日志每个最大条数的key
     */
    static readonly s105: string;
    /**
     * 审图号（普通地图）
     */
    static readonly p65: string;
    /**
     * 审图号（卫星地图）
     */
    static readonly s65: string;
    /**
     * 审图号 （地形图）
     */
    static readonly v65: string;
    /**
     * v4请求地址
     */
    static readonly a116: string;
    /**
     * 地形图鉴权接口
     */
    static readonly y101: string;
    static readonly b116: string;
    static readonly c116: string;
    static readonly d116: string;
    /**
     * v3请求地址
     */
    static readonly e116: string;
    /**
     * REST 域名
     */
    static readonly f116: string;
    /**
     * REST 域名
     */
    static readonly g116: string;
    static readonly HTTP: number;
    static readonly HTTPS: number;
    static readonly l103: string;
}
