// @keepTs
// @ts-nocheck
/**
 * @author zxy
 * @data 2020/9/25
 */
export declare class g22 {
    static readonly h116: string;
    static readonly i116: string;
    static readonly j116: string;
    static readonly k116: string;
    static readonly l116: string;
    static readonly m116: string;
    static readonly n116: string;
    static readonly o116: string;
    static readonly p116: string;
    static readonly q116: string;
    static readonly q38: string;
    /**
     * 默认marker标识
     */
    static readonly r116: string;
    static readonly s116: string;
    static readonly t116: string;
    /**
     * 更新地图资源
     */
    static readonly u116: number;
    /**
     *  默认Marker图标的高度，像素
     */
    static readonly n23: number;
    /**
     *  默认Marker图标的宽度，像素
     */
    static readonly l23: number;
    private static density;
    static n22(): number;
    static s63(value: number): void;
}
