// @keepTs
// @ts-nocheck
import { i73 } from './GLOverlay';
import { w24 } from './AVectorCrossAttr';
import { CrossVectorOverlay } from './CrossVectorOverlay';
import { p66 } from './interface/IAMapNativeDelegate';
export declare class t120 extends i73 {
    private k146;
    constructor(h146: number, i146: p66, code: number);
    m121(f146: w24, link: Int8Array, count: number): number;
    g121(d146: boolean, e146: number): void;
    h121(c146: number): void;
    i121(b146: number): void;
    n121(z145: CrossVectorOverlay, a146: boolean): void;
    i107(): void;
}
