// @keepTs
// @ts-nocheck
import { IAMap } from './interface/IAMap';
export declare class t60 {
    static readonly o68 = 2;
    static readonly p68 = 10;
    static readonly q68 = 6;
    static readonly r68 = 30;
    static readonly s68 = 60;
    static readonly t68 = 10;
    static readonly u68 = 15;
    static readonly v68 = 30;
    static readonly w68 = 40;
    /**
     * 最小间隔，相当于最大刷新频率为100
     */
    static readonly x68: number;
    private static readonly o153;
    private static readonly p153;
    w132?: IAMap;
    static readonly TAG: string;
    private f69;
    private q153;
    private r153;
    s153: boolean;
    private m69;
    t60(n153: IAMap): void;
    w64(): void;
    b16(): void;
}
