// @keepTs
// @ts-nocheck
export declare class d38 {
    static readonly j64: string;
    static readonly l162: string;
    static readonly m162: string;
    static readonly n162: string;
    static readonly v43: string;
    static readonly m64: string;
    static readonly g96: string;
    static readonly l64: string;
    static readonly y93: string;
    static readonly o38: string;
    static readonly j96: string;
    static readonly q64: string;
    static readonly o162: string;
    static readonly x93: string;
    static readonly p162 = "TERRAINTILEOVERLAY";
    static readonly w93 = "AMAP3DMODELTILE";
    static readonly p64: string;
}
