// @keepTs
// @ts-nocheck
/**
 * 渲染引擎地图poi信息
 */
export declare class o66 {
    name: string;
    poiid: string;
    mainKey: bigint;
    subKey: bigint;
    poiType: bigint;
    subType: bigint;
    isFocus: boolean;
    timestamp: bigint;
    extendInfo: string;
    screenX: number;
    screenY: number;
    longitude: number;
    latitude: number;
    z: number;
    iconXMin: bigint;
    iconXMax: bigint;
    iconYMin: bigint;
    iconYMax: bigint;
}
