// @keepTs
// @ts-nocheck
import { Marker } from "../api/model/Marker";
/**
 * 原生view覆盖物包装类
 */
export declare class h179 {
    private static readonly z179;
    private marker;
    private a180;
    private b180;
    private c180;
    private d180;
    private e180;
    private isInfoWindowShown;
    private f180;
    private g180;
    private h180;
    constructor(marker: Marker);
    /**
     * 获取覆盖物view
     *
     * @return 覆盖物view
     */
    y179(): PixelMap | undefined;
}
