// @keepTs
// @ts-nocheck
import { SDKInfo } from "@amap/amap_lbs_common";
export declare class r38 {
    private static readonly s38;
    private static t38;
    private static u38;
    private static mContext;
    static v38: SDKInfo;
    /**
     * 用来判断是否需要逆地理缓存
     */
    private static readonly w38;
    /**
     * 请求参数限制
     */
    private static readonly x38;
    private static readonly y38;
    private static readonly z38;
    private static readonly a39;
    private static readonly b39;
    /**
     * 参数限制
     */
    private static readonly c39;
    static getInstance(context: Context): r38;
    private constructor();
}
