// @keepTs
// @ts-nocheck
import { WalkRouteQueryV2 } from "../../route/WalkRouteQueryV2";
import { WalkRouteResultV2 } from "../../route/WalkRouteResultV2";
import { b7 } from "./BasicLBSRestHandler";
export declare class b53 extends b7<WalkRouteQueryV2, WalkRouteResultV2> {
    constructor(context: Context, e53: WalkRouteQueryV2);
    protected m6(): string;
    protected n6(c53: string): WalkRouteResultV2;
    k6(): string;
}
