// @keepTs
// @ts-nocheck
import { p199 } from "./net/AbstractProtocalHandler";
import { k203 } from "./OfflineInitBean";
/**
 * @author zxy
 */
export declare class u192 extends p199<string, k203> {
    private static readonly t203;
    constructor(context: Context, s203: string);
    protected y199(r203: string): string;
    protected z199(): string;
    protected a200(): Map<String, String>;
    private static readonly u203;
    private static readonly v203;
    private static readonly w203;
    private static readonly x203;
    protected n126(p203: string): k203;
}
