// @keepTs
// @ts-nocheck
import { e9 } from "./CityObject";
/**
 * 删除省份城市
 *
 * @author zxy94400
 */
export declare class c201 {
    private context;
    constructor(context: Context);
    d203(h208: e9): void;
    private i208;
    /**
     * 删除已下载的离线数据 包括下载进度记录和离线数据文件<br>
     * 但不包含当前城市离线数据外的缓存数据
     *
     * @return false 表示删除失败
     */
    private j208;
    /**
     * 删除已下载的离线数据 包括下载进度记录和离线数据文件<br>
     * 但不包含当前城市离线数据外的缓存数据
     *
     * @return false 表示删除失败
     */
    private k208;
}
